### ISSUE TITLE
CSS in Html Doc

### ISSUE THREAD

**Issue by UtkarshGD** [UtkarshDeoli/Zerodha#1]
Hey there is CSS in html document i can you fix that just put it in the CSS file thank you

**Comment by UtkarshDeoli** [comment]
ok on it

**Comment by SharkyBytes** [comment]
Hey i will help you out...assign this to me

**Comment by UtkarshDeoli** [comment]
Already done buddy will just close the issue now @SharkyBytes

**Comment by UtkarshDeoli** [comment]
Moved all Styles to CSS file
